import { z } from "zod";

/**
 * Outpost "news/lore" content — the Oregon Trail "fort news" analog. Ambient
 * colonist lines the player overhears when docking at an outpost. Generated by
 * scripts/genai-lore.ts, interpreted by the M5 outpost screen.
 */
export const outpostLoreSchema = z.object({
  outpost: z.string().min(1),
  lines: z.array(z.string().min(1).max(160)).min(1).max(8),
});

export const loreFileSchema = z.array(outpostLoreSchema);

export type OutpostLore = z.infer<typeof outpostLoreSchema>;
